package com.app.model;

public enum InfoCodes {

    CONTROLLERS("CONTROLLERS"),
    VALIDATION("VALIDATION"),
    SECURITY("SECURITY"),
    FILE_UPLOAD("FILE_UPLOAD"),
    FILE_UTILITIES("FILE_UTILITIES"),
    FILE_MANAGER("FILE_MANAGER"),
    SERVICE_CART("CART_SERVICE"),
    SERVICE_COMPANY("COMPANY_SERVICE"),
    SERVICE_DELIVERY("DELIVERY_ADDRESS_SERVICE"),
    SERVICE_PRODUCT("PRODUCT_SERVICE"),
    SERVICE_FILES("FILES_SERVICE"),
    SERVICE_EMAIL("EMAIL_SERVICE"),
    SERVICE_SECURITY("SECURITY_SERVICE"),
    SERVICE_USER("USER_SERVICE"),
    UNKNOWN("UNKNOWN");

    private String code;

    InfoCodes(String code) {
        this.code = code;
    }
}