version: '3.8'

services:
  mysql1:
    image: mysql:latest
    volumes:
      - mysql1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: platform
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
      MYSQL_TCP_PORT: 3306
    ports:
      - '3306:3306'
    expose:
      - 3306

volumes:
  mysql1: