package com.app.exceptions;

public enum ExceptionCodes {

    CONTROLLERS("CONTROLLERS_EXCEPTION"),
    LAYOUT("LAYOUT_EXCEPTION"),
    MODEL("MODEL_EXCEPTION"),
    REPOSITORY("REPOSITORY_EXCEPTION"),
    VALIDATION("VALIDATION_EXCEPTION"),
    SECURITY("SECURITY_EXCEPTION"),
    SERVICE_CART("CART_SERVICE_EXCEPTION"),
    SERVICE_COMPANY("COMPANY_SERVICE_EXCEPTION"),
    SERVICE_DELIVERY("DELIVERY_ADDRESS_SERVICE_EXCEPTION"),
    SERVICE_PRODUCT("PRODUCT_SERVICE_EXCEPTION"),
    SERVICE_SECURITY("SECURITY_SERVICE_EXCEPTION"),
    SERVICE_USER("USER_SERVICE_EXCEPTIO"),
    OTHER("OTHER_MINOR_EXCEPTIONS");

    private String exceptionCode;

    ExceptionCodes(String exceptionCode) {
        this.exceptionCode = exceptionCode;
    }
}